# Generated by Django 4.1.6 on 2023-02-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
