# Generated by Django 4.1.6 on 2023-02-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
